name: Cypress Tests - Cypress Beginner

on:
  push:
    branches:
      - main
    paths:
      - 'cypress_begginer/**/*.js'
      - 'cypress_begginer/**/*.json'
      - 'cypress_begginer/**/*.yml'

jobs:
  cypress_begginer-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: Install dependencies
        run: npm install
        working-directory: ./cypress_begginer

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./cypress_begginer
